server:
 port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: hcn
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        envers:
          enabled: true
        hbm2ddl:
          auto: update
